### ISSUE TITLE
无法编译啊？

### ISSUE THREAD

**Issue by robinfoxnan** [iineva/tdesktop-builder#1]
1>------ 已启动生成: 项目: codegen_lang, 配置: Debug Win32 ------
1>call ninja.exe -C ..\out\Debug\ -k0 codegen_lang
1>ninja: Entering directory `..\out\Debug\'
1>[1/11] CXX SourceFiles\codegen\common\codegen_lang.logging.obj
1>FAILED: SourceFiles/codegen/common/codegen_lang.logging.obj
1>ninja -t msvc -e environment.x86 -- "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x86\cl.exe" /nologo /showIncludes /FC @SourceFiles\codegen\common\codegen_lang.logging.obj.rsp /c ..\..\Telegram\SourceFiles\codegen\common\logging.cpp /FoSourceFiles\codegen\common\codegen_lang.logging.obj /Fdcodegen_lang.pdb
1>ninja: fatal: CreateProcess: 系统找不到指定的文件。
1>

**Comment by robinfoxnan** [comment]
有微信号码或者QQ号码么，请教一下

**Comment by robinfoxnan** [comment]
重新refresh.bat执行后，各种报错，差别怎么会这么大呢

**Comment by iineva** [comment]
请严格跟着文档的步骤操作，不需要refresh这一步，重新做一次试试

**Comment by robinfoxnan** [comment]
嗯，我重新装了虚拟机，这次编译成功了，我想问一下，默认的这个服务器，注册时候能收到短信么？
我试了怎么没有反应呢

**Comment by iineva** [comment]
chatengine没有实现发送短信，需要自己实现，短信验证码默认是12345，仔细看文档里面写了
